/**
 * Master Template Registry Dokumen Resmi Pilkades Kabupaten Tegal
 * Berdasarkan: Perbup Tegal No. 27 Tahun 2018 jo Perbup Tegal No. 31 Tahun 2019
 * 
 * Aturan Paten Sistem:
 * 1. Seluruh nomor dokumen (SK, Berita Acara, Surat, Model, Formulir) KOSONG / INPUT MANUAL (tanpa auto-generate).
 * 2. Nomenklatur lembaga: "PANITIA PEMILIHAN KEPALA DESA" (bukan istilah buatan UI).
 * 3. Seluruh atribut institusi dan data pemilih bersumber secara dinamis dari database.
 */

export type DocumentCategory =
  | "PEMILIH"
  | "PENJARINGAN_CALON"
  | "PENETAPAN_CALON"
  | "LOGISTIK_SURAT_SUARA"
  | "PEMUNGUTAN_PENGHITUNGAN"
  | "PASCA_PEMILIHAN";

export interface OfficialLampiranDoc {
  id: string;
  nomorLampiranRomawi: string;
  nomorLampiranLabel: string;
  halamanPerbupAsli: string;
  kategori: DocumentCategory;
  judulResmi: string;
  jenisDokumen: "KEPUTUSAN_PANITIA" | "BERITA_ACARA" | "FORMULIR_MODEL" | "SURAT_PEMBERITAHUAN" | "SURAT_PERNYATAAN";
  dasarHukum: string;
  formatNomorManual: string; // Tampilan resmi garis / titik-titik jika nomor belum diinput manual
  deskripsiFungsi: string;
  komponenTerkait: string;
}

export const OFFICIAL_LAMPIRAN_REGISTRY: OfficialLampiranDoc[] = [
  // --- 1. TAHAPAN PEMILIH (DPS, DPTB, DPT) ---
  {
    id: "LAMPIRAN_XIII",
    nomorLampiranRomawi: "XIII",
    nomorLampiranLabel: "Lampiran XIII",
    halamanPerbupAsli: "81–82",
    kategori: "PEMILIH",
    judulResmi: "Contoh Keputusan Panitia tentang Penetapan Daftar Pemilih Sementara (DPS)",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 24 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK resmi pengesahan Daftar Pemilih Sementara oleh P2KD untuk diumumkan kepada masyarakat.",
    komponenTerkait: "tab-print-center / SK DPS",
  },
  {
    id: "LAMPIRAN_XIV",
    nomorLampiranRomawi: "XIV",
    nomorLampiranLabel: "Lampiran XIV",
    halamanPerbupAsli: "83",
    kategori: "PEMILIH",
    judulResmi: "Form Daftar Pemilih Sementara (DPS)",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 24 ayat (4) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "", // Formulir tabel tanpa nomor surat
    deskripsiFungsi: "Buku/Tabel format resmi cetak Daftar Pemilih Sementara untuk pengumuman dan uji publik warga.",
    komponenTerkait: "print-model-a1-dps / exportModelA1Pdf",
  },
  {
    id: "LAMPIRAN_XV",
    nomorLampiranRomawi: "XV",
    nomorLampiranLabel: "Lampiran XV",
    halamanPerbupAsli: "84–85",
    kategori: "PEMILIH",
    judulResmi: "Contoh Keputusan Panitia tentang Penetapan Daftar Pemilih Tambahan",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 27 ayat (3) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK penetapan warga pemilih baru yang memenuhi syarat selama masa tanggapan masyarakat atas DPS.",
    komponenTerkait: "tab-print-center / SK DP Tambahan",
  },
  {
    id: "LAMPIRAN_XVI",
    nomorLampiranRomawi: "XVI",
    nomorLampiranLabel: "Lampiran XVI",
    halamanPerbupAsli: "86",
    kategori: "PEMILIH",
    judulResmi: "Form Daftar Pemilih Tambahan",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 27 ayat (4) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Buku/Tabel format resmi cetak pemilih tambahan hasil perbaikan DPS.",
    komponenTerkait: "print-model-a2-dptb / exportModelA2Pdf",
  },
  {
    id: "LAMPIRAN_XVII",
    nomorLampiranRomawi: "XVII",
    nomorLampiranLabel: "Lampiran XVII",
    halamanPerbupAsli: "87–88",
    kategori: "PEMILIH",
    judulResmi: "Contoh Keputusan Panitia tentang Penetapan Daftar Pemilih Tetap (DPT)",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 28 ayat (5) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK hukum tertinggi penetapan DPT oleh Panitia Pemilihan Kepala Desa yang bersifat final dan mengikat.",
    komponenTerkait: "print-berita-acara / tab-finalisasi-dpt",
  },
  {
    id: "LAMPIRAN_XVIII",
    nomorLampiranRomawi: "XVIII",
    nomorLampiranLabel: "Lampiran XVIII",
    halamanPerbupAsli: "89",
    kategori: "PEMILIH",
    judulResmi: "Form Daftar Pemilih Tetap (DPT)",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 28 ayat (6) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Format resmi cetak buku induk DPT tingkat desa dan salinan DPT per TPS / Wilayah.",
    komponenTerkait: "print-model-a3-dpt / print-dpt-tps / exportModelA3Pdf",
  },

  // --- 2. PENJARINGAN & PENYARINGAN BAKAL CALON KADES ---
  {
    id: "LAMPIRAN_XIX",
    nomorLampiranRomawi: "XIX",
    nomorLampiranLabel: "Lampiran XIX",
    halamanPerbupAsli: "90–92",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Form/Blangko Penelitian Berkas Lamaran Persyaratan Bakal Calon Kepala Desa",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 33 ayat (5) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Instrumen verifikasi 20 item syarat administrasi calon kades.",
    komponenTerkait: "modul calon / verifikasi berkas",
  },
  {
    id: "LAMPIRAN_XX",
    nomorLampiranRomawi: "XX",
    nomorLampiranLabel: "Lampiran XX",
    halamanPerbupAsli: "93",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pemberitahuan Syarat Diragukan/Tidak Lengkap",
    jenisDokumen: "SURAT_PEMBERITAHUAN",
    dasarHukum: "Pasal 34 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "Nomor : ...... / Pan Pilkades / ...... / ......",
    deskripsiFungsi: "Surat dinas P2KD kepada bakal calon untuk melengkapi berkas yang belum memenuhi syarat.",
    komponenTerkait: "modul administrasi calon",
  },
  {
    id: "LAMPIRAN_XXI",
    nomorLampiranRomawi: "XXI",
    nomorLampiranLabel: "Lampiran XXI",
    halamanPerbupAsli: "94",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pengembalian Berkas Lamaran dan Tanda Terima",
    jenisDokumen: "SURAT_PEMBERITAHUAN",
    dasarHukum: "Pasal 35 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "Nomor : ...... / Pan Pilkades / ...... / ......",
    deskripsiFungsi: "Tanda terima resmi penyerahan/pengembalian dokumen berkas lamaran.",
    komponenTerkait: "modul administrasi calon",
  },
  {
    id: "LAMPIRAN_XXII",
    nomorLampiranRomawi: "XXII",
    nomorLampiranLabel: "Lampiran XXII",
    halamanPerbupAsli: "95",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Permohonan Cuti dari Kepala Desa (Petahana)",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 36 ayat (7) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat permohonan izin cuti Kepala Desa petahana kepada Bupati Tegal.",
    komponenTerkait: "modul calon petahana",
  },
  {
    id: "LAMPIRAN_XXIII",
    nomorLampiranRomawi: "XXIII",
    nomorLampiranLabel: "Lampiran XXIII",
    halamanPerbupAsli: "96",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Permohonan Cuti dari Perangkat Desa",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 37 ayat (4) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat permohonan cuti perangkat desa yang mendaftar bakal calon kades.",
    komponenTerkait: "modul calon perangkat desa",
  },
  {
    id: "LAMPIRAN_XXIV",
    nomorLampiranRomawi: "XXIV",
    nomorLampiranLabel: "Lampiran XXIV",
    halamanPerbupAsli: "97",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Izin Cuti bagi Perangkat Desa",
    jenisDokumen: "SURAT_PEMBERITAHUAN",
    dasarHukum: "Pasal 37 ayat (5) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Surat keputusan izin cuti resmi dari Kepala Desa/Camat bagi perangkat desa.",
    komponenTerkait: "modul calon perangkat desa",
  },
  {
    id: "LAMPIRAN_XXV",
    nomorLampiranRomawi: "XXV",
    nomorLampiranLabel: "Lampiran XXV",
    halamanPerbupAsli: "98",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Bertaqwa kepada Tuhan Yang Maha Esa",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf a Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat pernyataan bermeterai bakal calon kades bertakwa kepada Tuhan YME.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXVI",
    nomorLampiranRomawi: "XXVI",
    nomorLampiranLabel: "Lampiran XXVI",
    halamanPerbupAsli: "99",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Setia kepada Pancasila, UUD 1945, NKRI dan Pemerintah",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf b Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat pernyataan kesetiaan dasar negara bagi balon kades.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXVII",
    nomorLampiranRomawi: "XXVII",
    nomorLampiranLabel: "Lampiran XXVII",
    halamanPerbupAsli: "100",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Bersedia Dicalonkan dan Tidak Mengundurkan Diri",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf g Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat pernyataan komitmen tidak mundur setelah ditetapkan calon tetap.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXVIII",
    nomorLampiranRomawi: "XXVIII",
    nomorLampiranLabel: "Lampiran XXVIII",
    halamanPerbupAsli: "101",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Belum Pernah Menjabat Kepala Desa 3 Kali Masa Jabatan",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf l Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat pernyataan batasan maksimal 3 periode masa jabatan kades.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXIX",
    nomorLampiranRomawi: "XXIX",
    nomorLampiranLabel: "Lampiran XXIX",
    halamanPerbupAsli: "102",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Sanggup Bertempat Tinggal di Desa Setempat jika Terpilih",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf n Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Pernyataan kesanggupan domisili di desa setempat bila terpilih.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXX",
    nomorLampiranRomawi: "XXX",
    nomorLampiranLabel: "Lampiran XXX",
    halamanPerbupAsli: "103",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Menerima Hasil Pilkades dan Menjaga Kamtibmas",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf p Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Deklarasi siap menang dan siap kalah serta komitmen menjaga ketertiban umum.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXXI",
    nomorLampiranRomawi: "XXXI",
    nomorLampiranLabel: "Lampiran XXXI",
    halamanPerbupAsli: "104",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Surat Pernyataan Tidak Pernah Diberhentikan dari Jabatan Kepala Desa",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 38 ayat (2) huruf q Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Pernyataan bebas sanksi pemecatan/pelanggaran sumpah jabatan bagi mantan kades.",
    komponenTerkait: "blangko persyaratan calon",
  },
  {
    id: "LAMPIRAN_XXXII",
    nomorLampiranRomawi: "XXXII",
    nomorLampiranLabel: "Lampiran XXXII",
    halamanPerbupAsli: "105",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Daftar Riwayat Hidup Bakal Calon Kepala Desa",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 38 ayat (2) huruf s Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Biodata resmi format standar Perbup Tegal calon kepala desa.",
    komponenTerkait: "profil calon",
  },
  {
    id: "LAMPIRAN_XXXIII",
    nomorLampiranRomawi: "XXXIII",
    nomorLampiranLabel: "Lampiran XXXIII",
    halamanPerbupAsli: "106–108",
    kategori: "PENJARINGAN_CALON",
    judulResmi: "Contoh Berita Acara Penelitian Kelengkapan dan Keabsahan Berkas Administrasi Bakal Calon",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 39 ayat (14) Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara rapat pleno verifikasi keabsahan dokumen lamaran bakal calon kepala desa.",
    komponenTerkait: "modul administrasi calon",
  },

  // --- 3. PENETAPAN CALON & PENGUNDIAN NOMOR URUT ---
  {
    id: "LAMPIRAN_XXXIV",
    nomorLampiranRomawi: "XXXIV",
    nomorLampiranLabel: "Lampiran XXXIV",
    halamanPerbupAsli: "109–111",
    kategori: "PENETAPAN_CALON",
    judulResmi: "Contoh Keputusan Panitia tentang Penetapan Calon Kades yang Berhak Mengikuti Pemilihan",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 42 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK penetapan calon tetap kepala desa dari bakal calon yang memenuhi persyaratan.",
    komponenTerkait: "modul calon tetap",
  },
  {
    id: "LAMPIRAN_XXXV",
    nomorLampiranRomawi: "XXXV",
    nomorLampiranLabel: "Lampiran XXXV",
    halamanPerbupAsli: "112",
    kategori: "PENETAPAN_CALON",
    judulResmi: "Contoh Berita Acara Rapat Undian Penetapan Nomor Urut Calon",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 44 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara rapat pleno terbuka pengundian nomor urut calon kepala desa.",
    komponenTerkait: "modul undian nomor urut",
  },
  {
    id: "LAMPIRAN_XXXVI",
    nomorLampiranRomawi: "XXXVI",
    nomorLampiranLabel: "Lampiran XXXVI",
    halamanPerbupAsli: "113–115",
    kategori: "PENETAPAN_CALON",
    judulResmi: "Contoh Keputusan Panitia tentang Penetapan Hasil Pengundian Nomor Urut Calon",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 45 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK resmi penetapan nomor urut peserta pemilihan kepala desa.",
    komponenTerkait: "modul nomor urut calon",
  },

  // --- 4. LOGISTIK, SURAT SUARA & UNDANGAN C6 ---
  {
    id: "LAMPIRAN_XXXVII",
    nomorLampiranRomawi: "XXXVII",
    nomorLampiranLabel: "Lampiran XXXVII",
    halamanPerbupAsli: "116–122",
    kategori: "LOGISTIK_SURAT_SUARA",
    judulResmi: "Contoh Bentuk dan Ukuran Surat Suara Pilkades",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 48 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Spesifikasi baku tata letak, ukuran, dan lipatan surat suara (2 calon, 3 calon, 4 calon, 5 calon).",
    komponenTerkait: "modul logistik surat suara",
  },
  {
    id: "LAMPIRAN_XXXVIII",
    nomorLampiranRomawi: "XXXVIII",
    nomorLampiranLabel: "Lampiran XXXVIII",
    halamanPerbupAsli: "123",
    kategori: "LOGISTIK_SURAT_SUARA",
    judulResmi: "Contoh Surat Pemberitahuan/Surat Undangan dan Bukti Penerimaan",
    jenisDokumen: "SURAT_PEMBERITAHUAN",
    dasarHukum: "Pasal 50 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "Nomor : ...... / Pan Pilkades / ...... / ......",
    deskripsiFungsi: "Format resmi surat undangan pemilih ke TPS dan blangko bukti tanda terima fisik KPPS.",
    komponenTerkait: "print-form-c6",
  },
  {
    id: "LAMPIRAN_XXXIX",
    nomorLampiranRomawi: "XXXIX",
    nomorLampiranLabel: "Lampiran XXXIX",
    halamanPerbupAsli: "124–125",
    kategori: "LOGISTIK_SURAT_SUARA",
    judulResmi: "Contoh Berita Acara Penghitungan dan Penyerahan Surat Suara yang Disiapkan di TPS",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 52 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara serah terima logistik kartu suara & kotak suara dari P2KD kepada Panitia TPS.",
    komponenTerkait: "modul logistik TPS",
  },

  // --- 5. PEMUNGUTAN & PENGHITUNGAN SUARA ---
  {
    id: "LAMPIRAN_XL",
    nomorLampiranRomawi: "XL",
    nomorLampiranLabel: "Lampiran XL (XXXX)",
    halamanPerbupAsli: "126",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Berita Acara Rapat Pemungutan Suara di TPS",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 56 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara pembukaan rapat pemungutan suara jam 08.00 WIB di TPS.",
    komponenTerkait: "modul hari H TPS",
  },
  {
    id: "LAMPIRAN_XLI",
    nomorLampiranRomawi: "XLI",
    nomorLampiranLabel: "Lampiran XLI (XXXXI)",
    halamanPerbupAsli: "127",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Surat Pernyataan Pendamping Pemilih Berkebutuhan Khusus",
    jenisDokumen: "SURAT_PERNYATAAN",
    dasarHukum: "Pasal 57 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Surat pernyataan menjaga kerahasiaan pilihan bagi pendamping pemilih disabilitas/lansia.",
    komponenTerkait: "modul TPS khusus",
  },
  {
    id: "LAMPIRAN_XLII",
    nomorLampiranRomawi: "XLII",
    nomorLampiranLabel: "Lampiran XLII (XXXXII)",
    halamanPerbupAsli: "128",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Berita Acara Pelaksanaan Pemungutan Suara",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 59 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara penutupan masa pemungutan suara di TPS sebelum penghitungan.",
    komponenTerkait: "modul hari H TPS",
  },
  {
    id: "LAMPIRAN_XLIII",
    nomorLampiranRomawi: "XLIII",
    nomorLampiranLabel: "Lampiran XLIII (XXXXIII)",
    halamanPerbupAsli: "129",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Surat Mandat Saksi Calon Kepala Desa",
    jenisDokumen: "SURAT_PEMBERITAHUAN",
    dasarHukum: "Pasal 60 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Surat mandat resmi penunjukan saksi calon di TPS/Desa.",
    komponenTerkait: "modul saksi calon",
  },
  {
    id: "LAMPIRAN_XLIV",
    nomorLampiranRomawi: "XLIV",
    nomorLampiranLabel: "Lampiran XLIV (XXXXIV)",
    halamanPerbupAsli: "130–131",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Berita Acara Hasil Penghitungan Suara",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 63 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara perolehan suara sah para calon, suara tidak sah, dan surat suara sisa.",
    komponenTerkait: "modul rekapitulasi / hasil suara",
  },
  {
    id: "LAMPIRAN_XLV",
    nomorLampiranRomawi: "XLV",
    nomorLampiranLabel: "Lampiran XLV (XXXXV)",
    halamanPerbupAsli: "132–133",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Keputusan Panitia tentang Penghentian Pilkades Karena Force Majeur",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 67 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK penundaan/penghentian sementara Pilkades akibat bencana alam atau kerusuhan.",
    komponenTerkait: "modul tanggap darurat",
  },
  {
    id: "LAMPIRAN_XLVI",
    nomorLampiranRomawi: "XLVI",
    nomorLampiranLabel: "Lampiran XLVI (XXXXVI)",
    halamanPerbupAsli: "134",
    kategori: "PEMUNGUTAN_PENGHITUNGAN",
    judulResmi: "Contoh Lembar Catatan Penghitungan Suara (Tally Sheet)",
    jenisDokumen: "FORMULIR_MODEL",
    dasarHukum: "Pasal 62 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "",
    deskripsiFungsi: "Lembar plano coretan / tally turus hitung suara di papan pleno TPS.",
    komponenTerkait: "modul rekapitulasi suara",
  },

  // --- 6. PASCA PEMILIHAN & PENETAPAN TERPILIH ---
  {
    id: "LAMPIRAN_XLVII",
    nomorLampiranRomawi: "XLVII",
    nomorLampiranLabel: "Lampiran XLVII (XXXXVII)",
    halamanPerbupAsli: "135–136",
    kategori: "PASCA_PEMILIHAN",
    judulResmi: "Contoh Keputusan Panitia tentang Penetapan Calon yang Memperoleh Suara Terbanyak",
    jenisDokumen: "KEPUTUSAN_PANITIA",
    dasarHukum: "Pasal 68 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "SK penetapan resmi Kepala Desa terpilih untuk disampaikan kepada BPD dan Bupati Tegal.",
    komponenTerkait: "modul pemenang pilkades",
  },
  {
    id: "LAMPIRAN_XLVIII",
    nomorLampiranRomawi: "XLVIII",
    nomorLampiranLabel: "Lampiran XLVIII (XXXXVIII)",
    halamanPerbupAsli: "137",
    kategori: "PASCA_PEMILIHAN",
    judulResmi: "Contoh Berita Acara Serah Terima Jabatan Kepala Desa",
    jenisDokumen: "BERITA_ACARA",
    dasarHukum: "Pasal 72 Perbup Tegal No. 27 Tahun 2018 jo Perbup No. 31 Tahun 2019",
    formatNomorManual: "NOMOR : ............................................................",
    deskripsiFungsi: "Berita acara serah terima memori jabatan dari kades lama/pj kepada kades terlantik.",
    komponenTerkait: "modul serah terima jabatan",
  },
];

/**
 * Helper Standar Pemformatan Nomor Manual
 * Aturan: Jika nomor tidak diinput / bernilai string kosong,
 * tampilkan titik-titik panjang resmi untuk pengisian manual panitia.
 */
export function formatNomorManual(nomorInput?: string | null, placeholderTitik = "............................................................"): string {
  if (!nomorInput || !nomorInput.trim()) {
    return placeholderTitik;
  }
  return nomorInput.trim();
}
