plugins {
    id 'com.android.application'
}

android {
    namespace 'id.my.p2kdkalisalak.app'
    compileSdk 34

    defaultConfig {
        applicationId "id.my.p2kdkalisalak.app"
        minSdk 24
        targetSdk 34
        versionCode 22501
        versionName "2.25.01"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (file("release.keystore").exists()) {
                storeFile file("release.keystore")
                storePassword "p2kdkalisalak2027"
                keyAlias "p2kdkey"
                keyPassword "p2kdkalisalak2027"
            } else {
                initWith(signingConfigs.debug)
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.core:core:1.12.0'
}
